orgs:
  unbound-force:
    # Org settings
    billing_email: jay.flowers@gmail.com
    default_repository_permission: read
    has_organization_projects: true
    has_repository_projects: true
    members_can_create_repositories: true

    # Org members
    admins:
      - jflowers
      - marcusburghardt
      - sonupreetam
      - yvonnedevlinrh
    members:
      - beatrizmcouto
      - em-redhat
      - gxmiranda
      - hbraswelrh
      - jpower432
      - trevor-vaughan
      - tyraziel
      - sedonnel
      - cdaniels255

    # Teams
    teams:
      overlords:
        description: ""
        privacy: closed
        members:
          - beatrizmcouto
          - em-redhat
          - gxmiranda
          - hbraswelrh
          - jpower432
          - trevor-vaughan
          - yvonnedevlinrh
          - sedonnel
          - cdaniels255
        maintainers:
          - jflowers
          - marcusburghardt
          - sonupreetam
        repos:
          .github: write
          containerfile: write
          dewey: write
          gaze: write
          homebrew-tap: write
          replicator: write
          unbound-force: write
          website: write
          intake-kit: write
